#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         1
bspc config window_gap          10
bspc config normal_border_color "#bd93f9"
bspc config active_border_color "#50fa7b"
bspc config focused_border_color "#50fa7b"
